version: '3.3'

services:
    mongo:
        image: mongo:4.4
        environment:
            MONGO:INITDB_ROOT_USERNAME: root
            MONGO:INITDB_ROOT_PASSWORD: root
        ports:
            - 27017:27017
        volumes:
            - ./mongo_data:/data/db